# Generated by Django 2.2.28 on 2022-10-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vince', '0002_auto_20220719_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Product Name')),
                ('version_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Version')),
                ('version_value', models.CharField(max_length=100, verbose_name='Version Value')),
                ('case', models.ManyToManyField(to='vince.VulnerabilityCase')),
                ('cve_affected_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vince.CVEAffectedProduct')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vince.Contact')),
            ],
        ),
    ]