# Generated by Django 2.2.28 on 2022-11-07 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vince', '0004_auto_20221028_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vince.VulnerabilityCase'),
        ),
    ]