# Generated by Django 2.2.28 on 2022-12-07 21:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vince', '0006_auto_20221108_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sector',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Chemical'), (2, 'Commercial Facilities'), (3, 'Communications'), (4, 'Critical Manufactoring'), (5, 'Dams'), (6, 'Defense Industrial Base'), (7, 'Emergency Services'), (8, 'Energy'), (9, 'Financial'), (10, 'Food and Agriculture'), (11, 'Government Facilities'), (12, 'Healthcare and Public Health'), (13, 'Information Technology'), (14, 'Nuclear Reactors, Materials, and Waste'), (15, 'Transportation Systems'), (16, 'Water and Wastewater Systems')], max_length=38, null=True),
        ),
    ]