# Generated by Django 2.2.28 on 2022-12-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vince', '0007_product_sector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='sector',
        ),
        migrations.AddField(
            model_name='product',
            name='sector',
            field=models.ManyToManyField(blank=True, null=True, to='vince.Sector'),
        ),
    ]