# Generated by Django 2.2.28 on 2022-12-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vince', '0008_auto_20221210_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sector',
            field=models.ManyToManyField(to='vince.Sector'),
        ),
    ]