# Generated by Django 2.2.28 on 2022-12-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vince', '0009_auto_20221211_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cve',
        ),
        migrations.AddField(
            model_name='product',
            name='cve',
            field=models.ManyToManyField(to='vince.CVEAllocation'),
        ),
    ]