# Generated by Django 2.2.28 on 2023-01-06 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vince', '0010_auto_20221215_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='version_value',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Version Value'),
        ),
    ]